create table public.tb_users(username text primary key, role text not null check(role in ('owner','member')), salt text not null,password_hash text not null,created_at timestamptz not null default now());
create unique index tb_only_two_owners on public.tb_users(username) where role='owner';
alter table public.tb_users add constraint tb_owner_names check(role<>'owner' or username in ('greyson','expireddumpling'));
create table public.tb_settings(name text primary key,value jsonb not null);
insert into public.tb_settings(name,value) values('site_assets','{"logo_url":"https://raw.githubusercontent.com/hoomanthatlikeschocolate-stack/terrariumbuilds/main/public/terrarium-logo.jpg","hero_url":"https://images.unsplash.com/photo-1767131543136-4af77f4d419b?auto=format&fit=crop&fm=jpg&ixlib=rb-4.1.0&q=82&w=1600","hero_alt":"A lush planted glass terrarium with moss, ferns, wood, stones, and layered soil","hero_caption":"A little world, built by hand."}'::jsonb) on conflict(name) do nothing;
create table public.tb_sessions(token_hash text primary key,username text references public.tb_users(username) on delete cascade,kind text not null check(kind in ('gateway','owner','member')),expires_at timestamptz not null);
create index on public.tb_sessions(expires_at);
create index on public.tb_sessions(username);
create table public.tb_attempts(id bigint generated always as identity primary key,key text not null,created_at timestamptz not null default now());
create index on public.tb_attempts(key,created_at);
create table public.tb_products(id uuid primary key default gen_random_uuid(),name text not null,description text not null default '',category text not null default 'Supplies',price_cents integer check(price_cents>=0),stock integer not null default 0 check(stock>=0),published boolean not null default false,image_url text not null default '',checkout_url text not null default '',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.tb_tutorials(id uuid primary key default gen_random_uuid(),title text not null,animal text not null,summary text not null default '',difficulty text not null default 'Beginner',materials text not null default '',steps jsonb not null default '[]',note text not null default '',sources jsonb not null default '[]',image_url text not null default '',published boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.tb_chat(id uuid primary key default gen_random_uuid(),username text not null references public.tb_users(username),message text not null default '',image_url text not null default '',created_at timestamptz not null default now());
create index on public.tb_chat(username);
create table public.tb_orders(id uuid primary key default gen_random_uuid(),username text references public.tb_users(username),name text not null,email text not null,items jsonb not null,total_cents integer not null check(total_cents>=0),note text not null default '',status text not null default 'requested' check(status in ('requested','contacted','paid','fulfilled','cancelled')),created_at timestamptz not null default now());
create index on public.tb_orders(username);
alter table public.tb_users enable row level security;
alter table public.tb_settings enable row level security;
alter table public.tb_sessions enable row level security;
alter table public.tb_attempts enable row level security;
alter table public.tb_products enable row level security;
alter table public.tb_tutorials enable row level security;
alter table public.tb_chat enable row level security;
alter table public.tb_orders enable row level security;
revoke all on public.tb_users,public.tb_settings,public.tb_sessions,public.tb_attempts,public.tb_products,public.tb_tutorials,public.tb_chat,public.tb_orders from anon,authenticated;
grant all on public.tb_users,public.tb_settings,public.tb_sessions,public.tb_attempts,public.tb_products,public.tb_tutorials,public.tb_chat,public.tb_orders to service_role;
grant usage,select on sequence public.tb_attempts_id_seq to service_role;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('terrariumbuilds','terrariumbuilds',true,3145728,array['image/jpeg','image/png','image/webp']);
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('terrariumbuilds-chat','terrariumbuilds-chat',false,3145728,array['image/jpeg','image/png','image/webp']);
